FROM ubuntu:20.04

# Exporting a variable to install pkgs without any interactive questions
ENV DEBIAN_FRONTEND=noninteractive

# Installing nginx
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends nginx git  \
    && rm -rf /var/lib/apt/lists/*

# Copying the local entrypoint.sh file to /entrypoint.sh in the docker image
COPY ./entrypoint.sh /entrypoint.sh

RUN git config --global http.sslverify false  && git clone https://github.com/peerajak/Checkpoint21_WebdevRobotics.git tortoisebot_webapp && \
cd tortoisebot_webapp && git checkout checkpoint22 && \
cp -r * /var/www/html


# /bin/bash is the command we want to execute when running a docker container
ENTRYPOINT ["/bin/bash"]

# We want /bin/bash to execute our /entrypoint.sh when container starts
CMD ["/entrypoint.sh"]
