version: '3.7'
services:

 
  tf2_webbridge_action_server:
    image: peerajakcp22/tortoisebot-ros1-waypoints:v1
    container_name: tf2_webbridge_action_server   
    networks:
      tortoisebot-ros1-bridge-network:
        ipv4_address: 172.19.0.3
    ports:
      - 9090:9090
      - 11315:11315
    environment:
      - ROS_MASTER_URI=http://172.19.0.2:11311
      - ROS_HOSTNAME=172.19.0.3
      - SLOT_ROSBRIDGE_PORT=20001
    command: "/tortoisebot_ws/entrypoint.sh"

networks:
    tortoisebot-ros1-bridge-network:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: "172.19.0.0/16"








