FROM tortoisebot-ros1-gazebo:try1

COPY ./keyboard /etc/default/keyboard

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ros-noetic-dwa-local-planner 
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ros-noetic-ira-laser-tools ros-noetic-teleop-twist-keyboard python3-wstool python3-rosdep ninja-build stow 

RUN mkdir /tortoisebot_ws/carto_ws && \
cd /tortoisebot_ws/carto_ws && \
wstool init src && \
wstool merge -t src https://raw.githubusercontent.com/cartographer-project/cartographer_ros/master/cartographer_ros.rosinstall && \
wstool update -t src

RUN sed -i 's/ <depend>libabsl-dev<\/depend>/<!-- depend>libabsl-dev<\/depend-->/' /tortoisebot_ws/carto_ws/src/cartographer/package.xml

RUN cd /tortoisebot_ws/carto_ws && rosdep init && \
rosdep update && \
rosdep install --from-paths src --ignore-src --rosdistro=noetic -y

RUN cd /tortoisebot_ws/src/ && git clone -b melodic-devel https://github.com/ros-perception/perception_pcl.git && \
git clone https://github.com/ros-perception/pcl_msgs && \
git clone -b noetic-devel https://github.com/jsk-ros-pkg/geometry2_python3.git 

RUN cd /tortoisebot_ws/carto_ws && \
rosdep install --from-paths src --ignore-src --rosdistro=noetic -y && \
src/cartographer/scripts/install_abseil.sh

RUN cd /tortoisebot_ws/carto_ws &&  source /tortoisebot_ws/devel/setup.bash &&catkin_make_isolated --install --use-ninja -j3 -l3 
RUN cd /tortoisebot_ws  && rm -rf devel install install_isolated devel_isolated 
RUN source /opt/ros/noetic/setup.bash && catkin_make -j3 -l3  

RUN source /tortoisebot_ws/devel/setup.bash 
RUN source /tortoisebot_ws/carto_ws/devel_isolated/setup.bash

RUN echo "source /tortoisebot_ws/devel/setup.bash" >> /root/.bashrc
RUN echo "source /tortoisebot_ws/carto_ws/devel_isolated/setup.bash" >> /root/.bashrc



# Set the working folder at startup
WORKDIR /tortoisebot_ws
#roslaunch tortoisebot_firmware server_bringup.launch
ENV ROS_DOMAIN_ID=1
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

# Define entrypoint
ENTRYPOINT ["/bin/bash", "-c", "source /tortoisebot_ws/devel/setup.bash && source /tortoisebot_ws/carto_ws/devel_isolated/setup.bash &&roslaunch tortoisebot_firmware server_bringup.launch"]



