FROM ros:noetic-ros-core-focal

COPY ./keyboard /etc/default/keyboard

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y git ros-noetic-joy ros-noetic-teleop-twist-joy ros-noetic-teleop-twist-keyboard ros-noetic-amcl ros-noetic-map-server ros-noetic-move-base ros-noetic-urdf ros-noetic-xacro ros-noetic-rqt-image-view ros-noetic-gmapping ros-noetic-navigation ros-noetic-joint-state-publisher ros-noetic-robot-state-publisher ros-noetic-slam-gmapping ros-noetic-dwa-local-planner ros-noetic-joint-state-publisher-gui ros-noetic-ira-laser-tools ros-noetic-compressed-image-transport ros-noetic-camera-info-manager python3-wstool python3-rosdep ninja-build stow libraspberrypi-dev libraspberrypi0

SHELL ["/bin/bash", "-c"]

# Create a Catkin workspace and clone Tortoisebot repos
RUN source /opt/ros/noetic/setup.bash \
 && mkdir -p /tortoisebot_ws/src \
 && cd /tortoisebot_ws/src \
 && catkin_init_workspace 
RUN cd /tortoisebot_ws/src && git clone -b noetic https://github.com/rigbetellabs/tortoisebot.git 


# # Build the Catkin workspace and ensure it's sourced
RUN source /opt/ros/noetic/setup.bash \
 && cd /tortoisebot_ws \
 && catkin_make
RUN echo "source /tortoisebot_ws/devel/setup.bash" >> ~/.bashrc


RUN mkdir -p /tortoisebot_ws/carto_ws && \
cd /tortoisebot_ws/carto_ws && \
wstool init src && \
wstool merge -t src https://raw.githubusercontent.com/cartographer-project/cartographer_ros/master/cartographer_ros.rosinstall && \
wstool update -t src

RUN sed -i 's/ <depend>libabsl-dev<\/depend>/<!-- depend>libabsl-dev<\/depend-->/' /tortoisebot_ws/carto_ws/src/cartographer/package.xml

RUN rm -f /etc/ros/rosdep/sources.list.d/20-default.list
RUN cd /tortoisebot_ws/carto_ws && rosdep init && \
rosdep update && \
rosdep install --from-paths src --ignore-src --rosdistro=noetic -y

RUN cd /tortoisebot_ws/src/ && git clone -b melodic-devel https://github.com/ros-perception/perception_pcl.git && \
git clone https://github.com/ros-perception/pcl_msgs && \
git clone -b noetic-devel https://github.com/jsk-ros-pkg/geometry2_python3.git 

RUN cd /tortoisebot_ws/carto_ws && \
rosdep install --from-paths src --ignore-src --rosdistro=noetic -y 
RUN  cd /tortoisebot_ws/carto_ws && src/cartographer/scripts/install_abseil.sh 

# RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends libpthread-stubs0-dev

ENV LD_LIBRARY_PATH='/opt/ros/noetic/lib'

RUN apt-get install -y python3-rpi.gpio

RUN source /opt/ros/noetic/setup.bash &&  cd /tortoisebot_ws/carto_ws && catkin_make_isolated --install --use-ninja -j1 -l1
RUN cd /tortoisebot_ws/carto_ws && source devel_isolated/setup.bash --install --use-ninja -j1 -l1 #<-at this position
RUN cd /tortoisebot_ws  && rm -rf devel install install_isolated devel_isolated 
COPY ./tortoisebot_slam_real_no_rviz.launch /tortoisebot_ws/src/tortoisebot/tortoisebot_slam/launch
RUN source /opt/ros/noetic/setup.bash &&  cd /tortoisebot_ws  &&  catkin_make -j1 -l1  

RUN source /tortoisebot_ws/carto_ws/devel_isolated/setup.bash
RUN source /tortoisebot_ws/devel/setup.bash --extend

RUN echo "source /tortoisebot_ws/carto_ws/devel_isolated/setup.bash" >> /root/.bashrc
RUN echo "source /tortoisebot_ws/devel/setup.bash --extend" >> /root/.bashrc




# Set the working folder at startup
WORKDIR /tortoisebot_ws
COPY ./chain_setup.sh /tortoisebot_ws/
COPY ./entrypoint_slam_real.sh /tortoisebot_ws/entrypoint.sh

COPY ./camerav2_410x308_30fps.launch /tortoisebot_ws/src/tortoisebot/raspicam_node/launch/

#CMD ["/bin/bash", "-c", "/tortoisebot_ws/entrypoint.sh"]
