version: '3.7'
services:

  tortoisebot-sim:
    image: tortoisebot-ros1-gazebo:try1
    container_name: tortoisebot-gazebo
    network_mode: host
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
      - DISPLAY=${DISPLAY} 
    command: bash -c "source /tortoisebot_ws/devel/setup.bash && roslaunch --wait tortoisebot_gazebo tortoisebot_playground.launch"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix        
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]


