version: '3.7'
services:

  tortoisebot-sim:
    image: peerajakcp22/tortoisebot-ros1-gazebo:v1
    container_name: tortoisebot-gazebo
    networks:
      tortoisebot-ros1-bridge-network:
        ipv4_address: 172.19.0.2
    environment:
      - DISPLAY=${DISPLAY} 
      - ROS_MASTER_URI=http://172.19.0.2:11311
      - ROS_HOSTNAME=172.19.0.2
    command: bash -c "source /tortoisebot_ws/devel/setup.bash && roslaunch tortoisebot_gazebo tortoisebot_playground.launch"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix      

networks:
    tortoisebot-ros1-bridge-network:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: "172.19.0.0/16"

