version: '3.7'
services:

  tortoisebot-sim:
    image: peerajakcp22/tortoisebot-ros1-gazebo:v1
    container_name: tortoisebot-gazebo
    network_mode: host
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
      - DISPLAY=${DISPLAY} 
    command: bash -c "source /tortoisebot_ws/devel/setup.bash && roslaunch --wait tortoisebot_gazebo tortoisebot_playground.launch"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix        
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

  tortoisebot-serverbringup:
    image: peerajakcp22/tortoisebot-ros1-slam:v1
    container_name: tortoisebot-serverbringup
    network_mode: host
    depends_on:
     tortoisebot-sim:
       condition: service_started
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
    command: bash -c "source /tortoisebot_ws/devel/setup.bash && source /tortoisebot_ws/carto_ws/devel_isolated/setup.bash &&roslaunch tortoisebot_firmware server_bringup.launch" 


  tortoisebot-slam:
    image: peerajakcp22/tortoisebot-ros1-slam:v1
    container_name: tortoisebot-slam
    network_mode: host
    depends_on:
      tortoisebot-serverbringup:
        condition: service_started
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
      - DISPLAY=${DISPLAY} 
    command: bash -c "source /tortoisebot_ws/devel/setup.bash && source /tortoisebot_ws/carto_ws/devel_isolated/setup.bash && roslaunch tortoisebot_slam tortoisebot_slam.launch" 
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix 
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

  rosbridge:
    image: peerajakcp22/tortoisebot-ros1-waypoints:v1
    container_name: rosbridge
    network_mode: host
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
    command: bash -c "source /tortoisebot_ws/devel/setup.bash && roslaunch course_web_dev_ros web.launch"

  tf2_web:
    image: peerajakcp22/tortoisebot-ros1-waypoints:v1
    container_name: tf2_web
    network_mode: host
    depends_on:
      tortoisebot-serverbringup:
        condition: service_started
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
    command: bash -c "source /tortoisebot_ws/devel/setup.bash && roslaunch course_web_dev_ros tf2_web.launch"

  action-server:
    image: peerajakcp22/tortoisebot-ros1-waypoints:v1
    container_name: action-server
    network_mode: host
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
    command: bash -c "source /tortoisebot_ws/devel/setup.bash && rosrun course_web_dev_ros tortoisebot_action_server.py"

  web-server:
    image: peerajakcp22/tortoisebot-ros1-webapp:v1
    container_name: web-server
    network_mode: host
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
    ports:
      - 8001:8001
    command: "entrypoint.sh"




