version: '3.7'
services:


  tortoisebot-slam:
    image: peerajakcp22/tortoisebot-ros1-slam:v1
    container_name: tortoisebot-slam
    networks:
      tortoisebot-ros1-bridge-network:
        ipv4_address: 172.19.0.4
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=http://172.19.0.2:11311
      - ROS_HOSTNAME=172.19.0.4
    command: "/tortoisebot_ws/entrypoint.sh"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix 

networks:
    tortoisebot-ros1-bridge-network:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: "172.19.0.0/16"

