version: '3.7'
services:

  #tortoisebot-ros2-sim:
  #  image: peerajakcp22/tortoisebot-ros2-real:v1
  #  container_name: tortoisebot-ros2-gazebo
  #  network_mode: host
  #  command: bash -c "source /ros2_ws/install/setup.bash && ros2 launch tortoisebot_bringup bringup.launch.py use_sim_time:=False"


  tortoisebot-ros2-slam:
    image: peerajakcp22/tortoisebot-ros2-real:v1
    container_name: tortoisebot-ros2-slam
    network_mode: host
    command: bash -c "source /ros2_ws/install/setup.bash && ros2 launch tortoisebot_bringup autobringup.launch.py use_sim_time:=False exploration:=True"














