version: '3.7'
services:

  tortoisebot-ros2-sim:
    image: peerajakcp22/tortoisebot-ros2-real:v1
    container_name: tortoisebot-ros2-gazebo
    privileged: true
    # Beware. If this is set, the topic/services cannot be communicate out of its own instance!. Except if you also unset CYCLONEDDS_URI environment variable, or set CYCLONEDDS_URI and ROS_DOMAIN_ID
    network_mode: host  
    environment:
        - ROS_DOMAIN_ID=1
        - CYCLONEDDS_URI=file:///var/lib/theconstruct.rrl/cyclonedds.xml
    command: bash -c "source /ros2_ws/install/setup.bash && ros2 launch tortoisebot_bringup bringup.launch.py use_sim_time:=False"


  tortoisebot-ros2-slam:
    image: peerajakcp22/tortoisebot-ros2-real-slam:v1
    container_name: tortoisebot-ros2-slam
    privileged: true
    # Beware. If this is set, the topic/services cannot be communicate out of its own instance!. Except if you also unset CYCLONEDDS_URI environment variable, or set CYCLONEDDS_URI and ROS_DOMAIN_ID
    network_mode: host  
    environment:
        - ROS_DOMAIN_ID=1
        - CYCLONEDDS_URI=file:///var/lib/theconstruct.rrl/cyclonedds.xml
    command: bash -c "source /ros2_ws/install/setup.bash && ros2 launch tortoisebot_bringup autobringup.launch.py use_sim_time:=False exploration:=True"














