FROM ros:galactic-ros-core-focal

# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]

# Install Git
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git ros-galactic-joint-state-publisher ros-galactic-robot-state-publisher ros-galactic-cartographer ros-galactic-cartographer-ros ros-galactic-gazebo-plugins ros-galactic-teleop-twist-keyboard  ros-galactic-teleop-twist-joy ros-galactic-xacro ros-galactic-nav2* ros-galactic-urdf python3-colcon-common-extensions && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends build-essential

# Create a Catkin workspace and clone Tortoisebot repos
#RUN source /opt/ros/galactic/setup.bash \
# && mkdir -p /ros2_ws/src \
# && cd /ros2_ws \
# && colcon build
#RUN cd /ros2_ws/src && git clone -b ros2-galactic https://github.com/rigbetellabs/tortoisebot.git


# Build the Catkin workspace and ensure it's sourced
#RUN source /opt/ros/galactic/setup.bash \
# && cd /ros2_ws \
# && colcon build
#RUN echo "source /opt/ros/galactic/setup.bash" >> /root/.bashrc
#RUN echo "source /ros2_ws/devel/setup.bash" >> /root/.bashrc

# Set the working folder at startup
WORKDIR /ros2_ws
