version: '3.7'
services:

  tortoisebot-ros2-sim:
    image: peerajakcp22/tortoisebot-ros2-gazebo:v1
    container_name: tortoisebot-ros2-gazebo
    network_mode: host
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
      - DISPLAY=${DISPLAY} 
    command: bash -c "source /ros2_ws/install/setup.bash && ros2 launch tortoisebot_bringup bringup.launch.py use_sim_time:=True"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix        
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]










